### ISSUE TITLE
Widget issue in Contentful for Backdrop/Unsplash image

### ISSUE THREAD

**Issue by denis-costello** [contentful/covid-19-site-template#37]
After setup when trying to edit the Backdrop image in Contentful I get the following error on the field entitled Unsplash URL (required):

The selected widget does not exist anymore.
Please select a valid widget in the Content Model section.

See screenshot:
<img width="329" alt="rsz_screenshot_2020-04-16_110854" src="https://user-images.githubusercontent.com/63240869/79437784-f21bf680-7fd2-11ea-9e7a-4286c7fe221e.png">

**Comment by dlitvakb** [comment]
Hey @denis-costello,

For some reason the extension was not included in the export - I'll take a look and see if I can update it when I have some time.

For the moment, you can recreate it yourself by creating a UI Extension with the following settings:
<img width="1349" alt="Screenshot 2020-04-16 at 14 00 12" src="https://user-images.githubusercontent.com/1032706/79455868-d2de9280-7fed-11ea-8a94-4ee8e5a5bd77.png">

There's also another UI extension for inlining tags, the settings are the following: 
<img width="1387" alt="Screenshot 2020-04-16 at 13 59 23" src="https://user-images.githubusercontent.com/1032706/79455915-e7bb2600-7fed-11ea-864b-e972bd739bd9.png">

Hope this helps,

Cheers

**Comment by denis-costello** [comment]
Thanks @dlitvakb That works
